server:
  error:
    whitelabel:
      enabled: false
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://158.160.13.203:5432/practice
    username: admin
    password: admin1
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false